### ISSUE TITLE
Upload your fork to CurseForge!

### ISSUE THREAD

**Issue by Carlosjrlu** [NikitaCartes/EasyAuth#1]
You should definetly upload the mod to CurseForge. So we could ask for it in Aternos.

**Comment by NikitaCartes** [comment]
https://www.curseforge.com/minecraft/mc-mods/easyauth
It's under review right now

**Comment by triphora** [comment]
> You should definetly upload the mod to CurseForge. So we could ask for it in Aternos.

Does Aternos not allow Modrinth mods? o.O

**Comment by triphora** [comment]
@Carlosjrlu Modrinth mods are allowed on Aternos now, btw.

**Comment by Carlosjrlu** [comment]
@wafflecoffee Didn't know that, it still needs to be a little bit more popular so curseforge page would maybe give it a little more exposure.
