### ISSUE TITLE
Publish on SimpleAuth's page [FeatureReq]

### ISSUE THREAD

**Issue by MenacingPerson** [NikitaCartes/EasyAuth#10]
**Is your feature request related to a problem? Please describe.**
I can't use this on aternos because it isn't popular enough.

**Describe the solution you'd like**
If this is posted on SimpleAuth's page we can successfully use it on aternos.

**Describe alternatives you've considered**
Maybe this mod could be popular enough?

**Additional context**

![image](https://user-images.githubusercontent.com/59611020/128589791-4b216b56-6e5c-4eee-987e-2f42fc609e7b.png)

**Comment by NikitaCartes** [comment]
samo_lego deprecated his mod, so it wouldn't be possible.

I wrote about my mod (even if it is not popular enough) on the Aternos Discord server, but unfortunately this is all I can do.
