### ISSUE TITLE
[BUG] Issue with Custom Translations and Configuration on Minecraft Server

### ISSUE THREAD

**Issue by plhappylemonpl** [NikitaCartes/EasyAuth#103]
**Versions**
* EasyAuth X.Y.Z - easyauth-mc1.20-3.0.19
* Fabric API X.Y.Z - fabric-api-0.87.0+1.20.1.jar

Hello,

I would like to address an issue related to server configuration. Unfortunately, I have encountered difficulties with the proper functioning of custom translations.

The situation is as follows: A friend of mine encouraged me to set up a Minecraft server based on the Fabric platform. Because several of my friends do not have premium Minecraft accounts, I decided to implement a login system on the server. After searching through numerous forums, I eventually came across information on Reddit regarding your mod called EasyAuth. I installed it and noticed that it also supports players with premium accounts. I was quite pleased with this prospect.

Consequently, I decided to add the mod to the "mods" folder on the server. After completing this step, I started the server, and during the initial login, I was prompted for a password. This wasn't an issue for me as I use a premium Minecraft account. I entered the command /register XYZ XYZ and then logged in with those credentials. Everything seemed to work fine, but the messages that appeared during login were in English.

As someone who strives for perfection, I decided to translate these messages into Polish. So, I entered the mod folder and noticed that a new file named "config.json" had been created. I inputted the appropriate translations for the message lines and executed the command /auth reload. Unfortunately, despite my efforts, the messages still remained in English. Perhaps I am doing something wrong, so I decided to restart the server, but the result was still the same.

I wondered if the issue might lie within the configuration file, so I attempted to change it. I removed the folder named "levelDBStore" for testing purposes, as I suspected that the configuration might be loaded once from the JSON file and then from the database. Unfortunately, this also didn't yield the expected results, and the messages continued to be in English.

As a result, I have decided to report this issue as a bug. I want to emphasize that despite my attempts to change the language in the configuration file, I have not observed any improvement. Below, I am providing a snippet of console logs that could be helpful in diagnosing the problem.

**Additional context**
config.json

{
  "main": {
    "allowEntityInteract": false,
    "maxLoginTries": 1,
    "kickTime": 120,
    "enableGlobalPassword": false,
    "globalPassword": null,
    "tryPortalRescue": true,
    "minPasswordChars": 4,
    "maxPasswordChars": -1,
    "usernameRegex": "^[a-zA-Z0-9_]{3,16}$",
    "sessionTimeoutTime": 3600,
    "spawnOnJoin": false,
    "databaseType": "",
    "MySQLHost": "localhost",
    "MySQLUser": "root",
    "MySQLPassword": "",
    "MySQLDatabase": "easyauth",
    "MySQLTableName": "easyauth",
    "MongoDBConnectionString": "mongodb://username:password@host:port/?options",
    "MongoDBDatabase": "easyauth",
    "premiumAutologin": true,
    "floodgateAutologin": false,
    "forcedOfflinePlayers": [],
    "hideUnauthenticatedPLayersFromPlayerList": false
  },
  "worldSpawn": {
    "dimension": "minecraft:overworld",
    "x": 0.0,
    "y": 64.0,
    "z": 0.0,
    "yaw": 0.0,
    "pitch": 0.0
  },
  "lang": {
    "enterPassword": "§6Musisz wprowadzic swoje haslo!",
    "enterNewPassword": "§4Musisz podac nowe haslo!",
    "wrongPassword": "§4Nieprawidlowe haslo!",
    "matchPassword": "§6Hasla musza byc identyczne!",
    "passwordUpdated": "§aTwoje haslo zostalo pomyslnie zaktualizowane!",
    "loginRequired": "§cMusisz uwierzytelnic sie!\n§6Uzyj /login lub /l do uwierzytelnienia!",
    "loginTriesExceeded": "§4Zbyt wiele prob logowania. Poczekaj kilka minut i sprobuj ponownie.",
    "globalPasswordSet": "§aGlobalne haslo zostalo pomyslnie ustawione!",
    "cannotChangePassword": "§cNie mozesz zmienic hasla!",
    "cannotUnregister": "§cNie mozesz anulowac rejestracji tego konta!",
    "notAuthenticated": "§cNie jestes uwierzytelniony!\n§6Sprobuj /login, /l lub /register.",
    "alreadyAuthenticated": "§6Juz jestes uwierzytelniony.",
    "successfullyAuthenticated": "§aJestes teraz uwierzytelniony.",
    "successfulLogout": "§aWylogowano pomyslnie.",
    "timeExpired": "§cCzas na uwierzytelnienie wygasl.",
    "registerRequired": "§6Wpisz /register \u003chaslo\u003e \u003chaslo\u003e, aby aktywowac to konto.",
    "alreadyRegistered": "§6Ta nazwa konta jest juz zarejestrowana!",
    "registerSuccess": "§aJestes teraz uwierzytelniony.",
    "userdataDeleted": "§aDane uzytkownika usuniete.",
    "userdataUpdated": "§aDane uzytkownika zaktualizowane.",
    "accountDeleted": "§aTwoje konto zostalo pomyslnie usuniete!",
    "configurationReloaded": "§aPlik konfiguracji zostal pomyslnie przeladowany.",
    "maxPasswordChars": "§6Haslo moze miec maksymalnie %d znakow!",
    "minPasswordChars": "§6Haslo musi miec co najmniej %d znakow!",
    "disallowedUsername": "§6Niedozwolone znaki w nazwie uzytkownika! Dozwolony wzorzec znakow: %s",
    "playerAlreadyOnline": "§cGracz %s jest juz online!",
    "worldSpawnSet": "§aSpawn dla logowania zostal pomyslnie ustawiony.",
    "corruptedPlayerData": "§cTwoje dane sa prawdopodobnie uszkodzone. Skontaktuj sie z administratorem.",
    "userNotRegistered": "§cTen gracz nie jest zarejestrowany!",
    "cannotLogout": "§cNie mozesz sie wylogowac!",
    "offlineUuid": "UUID offline dla %s to %s",
    "registeredPlayers": "Lista zarejestrowanych graczy:",
    "addToForcedOffline": "Gracz zostal pomyslnie dodany do listy forcedOfflinePlayers"
  },
  "experimental": {
    "preventAnotherLocationKick": true,
    "playerInvulnerable": true,
    "playerInvisible": true,
    "allowChat": false,
    "allowCommands": false,
    "allowedCommands": [],
    "allowMovement": false,
    "allowBlockUse": false,
    "allowBlockPunch": false,
    "allowItemDrop": false,
    "allowItemMoving": false,
    "allowItemUse": false,
    "allowEntityPunch": false,
    "debugMode": false,
    "useBCryptLibrary": false,
    "forcedOfflineUuids": false,
    "useSimpleAuthDatabase": false,
    "teleportationTimeoutInMs": 5,
    "enableAliases": true,
    "enableServerSideTranslation": true,
    "resetLoginAttemptsTime": 120,
    "floodgateLoaded": false,
    "floodgateBypassUsernameRegex": false,
    "verifiedOnlinePlayer": [],
    "skipAllAuthChecks": false
  }
}

**Additional context**
Consol log

C:\Users\LemoN\Downloads\serverfabric>java -Xmx2G -jar fabric-server-launch.jar nogui
Starting net.fabricmc.loader.impl.game.minecraft.BundlerClassPathCapture
[16:34:26] [main/INFO]: Loading Minecraft 1.20.1 with Fabric Loader 0.14.22
[16:34:27] [main/INFO]: Loading 57 mods:
        - easyauth 3.0.19
           |-- at_favre_lib_bcrypt 0.9.0
           |-- at_favre_lib_bytes 1.5.0
           |-- com_mysql_mysql-connector-j 8.0.33
           |-- de_mkammerer_argon2-jvm 2.11
           |-- de_mkammerer_argon2-jvm-nolibs 2.11
           |-- fabric-permissions-api-v0 0.2-SNAPSHOT
           |-- net_java_dev_jna_jna 5.12.1
           |-- org_iq80_leveldb_leveldb 0.12
           |-- org_iq80_leveldb_leveldb-api 0.12
           |-- org_mongodb_bson 4.7.2
           |-- org_mongodb_mongodb-driver-core 4.7.2
           |-- org_mongodb_mongodb-driver-sync 4.7.2
           |-- placeholder-api 2.1.1+1.20
           \-- server_translations_api 2.0.0+1.20
                \-- packet_tweaker 0.4.0+1.19.4
        - fabric-api 0.87.0+1.20.1
           |-- fabric-api-base 0.4.30+7abfd51577
           |-- fabric-api-lookup-api-v1 1.6.35+4d8536c977
           |-- fabric-biome-api-v1 13.0.10+b3afc78b77
           |-- fabric-block-api-v1 1.0.9+e022e5d177
           |-- fabric-blockrenderlayer-v1 1.1.40+b3afc78b77
           |-- fabric-client-tags-api-v1 1.1.1+97bb207577
           |-- fabric-command-api-v1 1.2.33+f71b366f77
           |-- fabric-command-api-v2 2.2.12+b3afc78b77
           |-- fabric-commands-v0 0.2.50+df3654b377
           |-- fabric-containers-v0 0.1.63+df3654b377
           |-- fabric-content-registries-v0 4.0.9+b3afc78b77
           |-- fabric-convention-tags-v1 1.5.4+a1a980da77
           |-- fabric-crash-report-info-v1 0.2.18+aeb40ebe77
           |-- fabric-data-generation-api-v1 12.2.2+1e61dba177
           |-- fabric-dimensions-v1 2.1.53+8536527b77
           |-- fabric-entity-events-v1 1.5.22+b3afc78b77
           |-- fabric-events-interaction-v0 0.6.1+e91849a877
           |-- fabric-events-lifecycle-v0 0.2.62+df3654b377
           |-- fabric-game-rule-api-v1 1.0.38+b04edc7a77
           |-- fabric-item-api-v1 2.1.27+b3afc78b77
           |-- fabric-item-group-api-v1 4.0.10+23d9108177
           |-- fabric-key-binding-api-v1 1.0.36+fb8d95da77
           |-- fabric-keybindings-v0 0.2.34+df3654b377
           |-- fabric-lifecycle-events-v1 2.2.21+b3afc78b77
           |-- fabric-loot-api-v2 1.1.39+b3afc78b77
           |-- fabric-loot-tables-v1 1.1.43+9e7660c677
           |-- fabric-message-api-v1 5.1.7+3265161977
           |-- fabric-mining-level-api-v1 2.1.49+b3afc78b77
           |-- fabric-model-loading-api-v1 1.0.2+709a987177
           |-- fabric-models-v0 0.4.1+9386d8a777
           |-- fabric-networking-api-v1 1.3.10+eeb8eb3677
           |-- fabric-networking-v0 0.3.50+df3654b377
           |-- fabric-object-builder-api-v1 11.1.1+6beca84877
           |-- fabric-particles-v1 1.1.1+201a23a077
           |-- fabric-recipe-api-v1 1.0.20+b3afc78b77
           |-- fabric-registry-sync-v0 2.3.2+4df89eb277
           |-- fabric-renderer-api-v1 3.1.2+6bdb2ed077
           |-- fabric-renderer-indigo 1.4.2+6bdb2ed077
           |-- fabric-renderer-registries-v1 3.2.45+df3654b377
           |-- fabric-rendering-data-attachment-v1 0.3.34+b3afc78b77
           |-- fabric-rendering-fluids-v1 3.0.27+b3afc78b77
           |-- fabric-rendering-v0 1.1.48+df3654b377
           |-- fabric-rendering-v1 3.0.7+b3afc78b77
           |-- fabric-resource-conditions-api-v1 2.3.5+ea08f9d877
           |-- fabric-resource-loader-v0 0.11.9+132c48c177
           |-- fabric-screen-api-v1 2.0.7+b3afc78b77
           |-- fabric-screen-handler-api-v1 1.3.29+b3afc78b77
           |-- fabric-sound-api-v1 1.0.12+b3afc78b77
           |-- fabric-transfer-api-v1 3.3.0+cdf060b277
           \-- fabric-transitive-access-wideners-v1 4.3.0+6c31357e77
        - fabricloader 0.14.22
        - java 20
        - minecraft 1.20.1
[16:35:08] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/LemoN/Downloads/serverfabric/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=SERVER
[16:35:08] [main/INFO]: Compatibility level set to JAVA_17
[16:35:17] [main/INFO]: [EasyAuth]: EasyAuth mod by samo_lego, NikitaCartes.
[16:35:17] [main/WARN]: [EasyAuth]: Disable enforce-secure-profile to allow offline players to join the server
[16:35:17] [main/WARN]: [EasyAuth]: For more info, see https://github.com/NikitaCartes/EasyAuth/issues/68
[16:35:17] [main/INFO]: [EasyAuth]: You have premiumAutologin enabled. Enable online-mode so that online player can not register.
[16:35:18] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[16:35:19] [main/INFO]: Loaded 7 recipes
[16:35:20] [main/INFO]: Loaded 1271 advancements
[16:35:20] [ForkJoinPool.commonPool-worker-1/INFO]: Loaded 34 translation keys
[16:35:20] [main/INFO]: Applied 0 biome modifications to 0 of 64 new biomes in 1.822 ms
[16:35:20] [Server thread/INFO]: Starting minecraft server version 1.20.1
[16:35:20] [Server thread/INFO]: Loading properties
[16:35:20] [Server thread/INFO]: Default game type: SURVIVAL
[16:35:20] [Server thread/INFO]: Generating keypair
[16:35:20] [Server thread/INFO]: Starting Minecraft server on *:25666
[16:35:20] [Server thread/INFO]: Using default channel type
[16:35:21] [Server thread/WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[16:35:21] [Server thread/WARN]: The server will make no attempt to authenticate usernames. Beware.
[16:35:21] [Server thread/WARN]: While this makes the game possible to play without internet access, it also opens up the ability for hackers to connect with any username they choose.
[16:35:21] [Server thread/WARN]: To change this, set "online-mode" to "true" in the server.properties file.
[16:35:21] [Server thread/INFO]: Preparing level "world"
[16:35:22] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[16:35:25] [Worker-Main-17/INFO]: Preparing spawn area: 0%
[16:35:25] [Worker-Main-17/INFO]: Preparing spawn area: 0%
[16:35:25] [Worker-Main-17/INFO]: Preparing spawn area: 0%
[16:35:25] [Worker-Main-17/INFO]: Preparing spawn area: 0%
[16:35:25] [Worker-Main-17/INFO]: Preparing spawn area: 0%
[16:35:25] [Worker-Main-17/INFO]: Preparing spawn area: 0%
[16:35:25] [Worker-Main-18/INFO]: Preparing spawn area: 7%
[16:35:25] [Worker-Main-5/INFO]: Preparing spawn area: 88%
[16:35:25] [Server thread/INFO]: Time elapsed: 3555 ms
[16:35:25] [Server thread/INFO]: Done (4.528s)! For help, type "help"
[16:35:28] [Server thread/INFO]: HappY_LemoN_PL[/192.168.0.4:65500] logged in with entity id 324 at (50.5, 77.0, -63.5)
[16:35:28] [Server thread/INFO]: HappY_LemoN_PL joined the game
[16:35:55] [Server thread/INFO]: [HappY_LemoN_PL: Set own game mode to Creative Mode]
[16:35:58] [Server thread/INFO]: [HappY_LemoN_PL: Set the time to 0]
[16:36:01] [Server thread/INFO]: [HappY_LemoN_PL: Set the time to 0]
[16:36:03] [Server thread/INFO]: [HappY_LemoN_PL: Set the weather to clear]
[16:49:34] [Server thread/INFO]: [EasyAuth]: You have premiumAutologin enabled. Enable online-mode so that online player can not register.
[16:49:34] [Server thread/INFO]: [EasyAuth]: Database connection closed successfully
auth reload
[16:51:35] [Server thread/INFO]: [EasyAuth]: You have premiumAutologin enabled. Enable online-mode so that online player can not register.
[16:51:35] [Server thread/INFO]: [EasyAuth]: Database connection closed successfully

**Comment by NikitaCartes** [comment]
1) Thanks for detailed issue especially for config and logs.
2) By default mod will [try to] send messages in language of your Minecraft client.
Polish should be supported: https://github.com/NikitaCartes/EasyAuth/blob/fabric-1.20/src/main/resources/data/easyauth/lang/pl_pl.json
3) You can disable this behavior by setting `enableServerSideTranslation` to false. Message will be sent as they presented in config.

Bonus: You may want to enable `online-mode` in `server.properties` so premium player can log in without password.

**Comment by plhappylemonpl** [comment]
Hello,

It's working! Thank you for your assistance. If possible, I recommend adding a message for premium players in the style of: "You have been automatically logged in as a premium player." Such a message would surely be helpful to some extent, especially for players who might occasionally be less familiar.

Best regards,
