### ISSUE TITLE
[BUG] Player unable to join server when premiumAutoLogin set to true (aternos server)

### ISSUE THREAD

**Issue by TechPro424** [NikitaCartes/EasyAuth#106]
**Versions**
* EasyAuth mc1.20-3.0.19
* Fabric API 0.89.0+1.20.1

**Describe the bug**
Player unable to join server when premiumAutoLogin set to true, they get the error message `Authentication servers are down. Please try again later, sorry!`
But I can join other servers so I know that auth servers are not the problem

**To Reproduce**
1.  Create a server with easyauth default config but set premiumautologin to true
2. try joining server
3. get the error, unable to join

**Expected behavior**
Should be able to join without issues

**Additional context**

**Comment by TechPro424** [comment]
Confirmed that online mod is set to true, still same issue

**Comment by NikitaCartes** [comment]
You trying to join with online or offline account?
Is there something in logs?

**Comment by TechPro424** [comment]
Oh, wait, I thought I included the logs, my bad 😅 
I'm trying to join with an online account

Log: https://mclo.gs/4RO1tTE
Config file: https://gist.github.com/TechPro424/d2af1865a9a4e6de8a7232f1597f42db

**Comment by NikitaCartes** [comment]
This looks like something wrong with your connection to Mojang servers. Can you check if that error persist without EasyAuth?

**Comment by NikitaCartes** [comment]
Feel free to reopen

**Comment by TechPro424** [comment]
It just started working again, I have no idea why
Sorry for taking your time 😅
