### ISSUE TITLE
Changing a player's password.

### ISSUE THREAD

**Issue by GitHubbingOuttaHere** [NikitaCartes/EasyAuth#108]
**Versions**
* EasyAuth 3.0.19
* Fabric API 0.89.1
* EasyWhitelist 1.0.1

**Describe the bug**
A player in a server of mine forgot their password, so naturally, they reached out to me about this. So I tried to use the `auth update uuid new_password`, but then the game says that the player is not registered. I got the uuid from the player info in Aternos, and I tried using the EasyWhitelist mod to change their uuid to something else using a random Minecraft uuid generator and tried to update the password, but to no avail. Is there a way to change an offline player's password? I seem to can't find where the mod stores the passwords for each player.
`
**To Reproduce**
1. Use the command `/auth update <UUID> <new password>`
2. Server should say that the player is not registered

**Expected behavior**
I should be able to change their password based on the uuid associated with them on the Aternos Board

**Additional context**
NOTE: The server is in offline mode (Aternos), which means any uuid can work, as long as the format's still intact. I used the associated UUID for the player to try and change their password. Only mods present are EasyAuth and EasyWhitelist.

**Comment by NikitaCartes** [comment]
With auth command uuid for lower-case nicknames should be used. You can get right uuid with `auth uuid <nickname>`

**Comment by GitHubbingOuttaHere** [comment]
Ah I see. Thanks again!

**Comment by realyukii** [comment]
on the [wiki](https://github.com/NikitaCartes/EasyAuth/wiki) it says: `Admin commands (require op privileges):`

how to create account with op privileges?

**Comment by NikitaCartes** [comment]
1) Vanilla op command
2) LuckPerms permission `easyauth.commands.auth.root`

**Comment by realyukii** [comment]
sorry, but I'm not too familiar with minecraft, wdym by "Vanilla op command" and "LuckPerms"?

**Comment by realyukii** [comment]
after skimming through [the wiki](https://minecraft.wiki/w/Tutorials/Setting_up_a_server), it seems there's `/op` command, but I'm not sure where I should type it, the chat box in the game says the command doesn't exists

**Comment by NikitaCartes** [comment]
Because you need to be op to run `/op` command :)

You can run `/op <your nickname>` in server console

**Comment by realyukii** [comment]
Ah yes, the wiki already mention it clearly: `To become or add an operator, type /op <targets> into the server console or gui`

I just doubt it will accept any input on stdin as it seems the server print stdout only, but I know for sure after tried your suggestion, thanks!
