### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Nicolol1234** [NikitaCartes/EasyAuth#109]
**Versions**
* EasyAuth 1.20-3.0.19.jar
* Fabric API 0.90.0+1.20.1.jar

**Describe the bug**
Crash on startup

**To Reproduce**
1. Install easyauth & luckperm (it seems that luckperm is the problem)
2. Start
3. see the crash

**Expected behavior**
Everything should work

**Additional context**
Logs:
https://mclo.gs/6esMVOw#L541

**Comment by NikitaCartes** [comment]
Did game successfully start without EasyAuth? I'm not sure that 5.4.104 works with 1.20.1

**Comment by Nicolol1234** [comment]
I found the reason of why it crashed, it's another mod whi conflict with everything
