### ISSUE TITLE
unregister command does not work[BUG]

### ISSUE THREAD

**Issue by Soham52** [NikitaCartes/EasyAuth#11]
**Versions**
* EasyAuth 1.9.5
* Fabric API 0.37.1

**Describe the bug**
/account unregister <pass> just logs out the player instead of deleting the account, it even shows the deleted your account text but after that when /registered is typed it shows account already registered 

**To Reproduce**
1. Run /account unregister <pass>
2. /register <pass> <pass>
3. See Error

**Expected behavior**
The Account should have been deleted and /register should have worked

**Additional context**
after unregistering /login <pass> still works

**Comment by NikitaCartes** [comment]
Thanks for report!

If you want you can test pre-release version. You can download it [here](https://github.com/NikitaCartes/EasyAuth/runs/3374662952) (click at `Artifacts` button)

**Comment by Soham52** [comment]
Thanks for fixing this so quick :)
