### ISSUE TITLE
[BUG] Crash after offline player registration.

### ISSUE THREAD

**Issue by ghost** [NikitaCartes/EasyAuth#111]
**Versions**
* EasyAuth 3.0.19
* Fabric API 0.90.4+1.20.2

**Describe the bug**
Crash after offline player registration.

**To Reproduce**
1.  Using offline players to access the server.
2.  Registering using `/register`.
3.  Server crash.

**Additional context**
Server logs: https://mclo.gs/rGylK3I
`/run/hs_err_pid1.log`: https://mclo.gs/bKxyj2E

**Comment by NikitaCartes** [comment]
https://github.com/NikitaCartes/EasyAuth/wiki/GLIBC-problems

**Comment by ghost** [comment]
Oh I should have thought of this question......
Sorry for taking your time
