### ISSUE TITLE
[BUG]uuid lookup result mismatch with data file in folder "playerdata"

### ISSUE THREAD

**Issue by Silverteal** [NikitaCartes/EasyAuth#118]
**Versions**
* EasyAuth 3.0.19
* Fabric API 0.91.0

**Describe the bug**
With operator typing /auth uuid Username, the terminal returns a uuid, which does not exist in "playerdata" folder.

**To Reproduce**
1. Go to terminal'
2. Type in /auth uuid D3f4u5t
3. See the error

**Comment by NikitaCartes** [comment]
It works as indented, because auth uuid show uuid that needed for mod.
I will change that system in future, but that's another issue.
