### ISSUE TITLE
[BUG] Cannot start server with version 3.0.21-SNAPSHOT

### ISSUE THREAD

**Issue by FutureLizard205** [NikitaCartes/EasyAuth#119]
**Versions**
* Minecraft 1.20.4
* EasyAuth 3.0.21-SNAPSHOT
* Fabric API 0.91.3

**Describe the bug**
Server always crashes upon starting.

**To Reproduce**
1. Download fabric server jar, set it up
2. Download Fabric API and EasyAuth and put them in the mods folder
3. Try to start the server

**Expected behavior**
The server would start

**Log**
[errorlog.txt](https://github.com/NikitaCartes/EasyAuth/files/13762092/errorlog.txt)

**Comment by NikitaCartes** [comment]
Thanks. Updated jar in release:
https://github.com/NikitaCartes/EasyAuth/releases/tag/3.0.21

**Comment by FutureLizard205** [comment]
No problem @NikitaCartes ! 
But now it actually crashes when it already has a config file. So, first time starting it it works, but second time it crashes similar to before. But after deleting the config folder, it starts up again (and fails on the next attempts).
[latest.log](https://github.com/NikitaCartes/EasyAuth/files/13763351/latest.log)

**Comment by NikitaCartes** [comment]
@FutureLizard205 I updated jar in [release](https://github.com/NikitaCartes/EasyAuth/releases/tag/3.0.21), it should work now

**Comment by FutureLizard205** [comment]
@NikitaCartes It does, thanks :)
