### ISSUE TITLE
[FeatureReq] Seperate Tablist

### ISSUE THREAD

**Issue by Soham52** [NikitaCartes/EasyAuth#12]
**Is your feature request related to a problem? Please describe.**
When a player joins the server, the server will display yhe player's name in the Tablist regaurdless of weather the player is authorised or not, this can be confusing for others in the server

**Describe the solution you'd like**
Do not display the names of players who have not been authorised and have a seperate Tablist

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by NikitaCartes** [comment]
@Soham52 How do you see it? Tab list with two columns? Or just hide unauthorized players from list?

Will a hiding "XXX joined server" message from player (and send it after authorization) be a good feature?
