### ISSUE TITLE
[BUG] "auth list" not working properly

### ISSUE THREAD

**Issue by RuggedTime** [NikitaCartes/EasyAuth#120]
**Versions**
easyauth-mc1.20-3.0.0-17.jar
fabric-api-0.84.0+1.20.1.jar

**Describe the bug**
this server has many players, one of them forgot his password...Then I want to reset his password to a new one, but "auth update uuid pwd" failed , and "auth list"  shows there is on one registered!
![image](https://github.com/NikitaCartes/EasyAuth/assets/46664847/f5734a38-15bc-45b4-b795-fd82e9c570c2)

**Comment by NikitaCartes** [comment]
You can use auth uuid <playerName> to get uuid for auth update command

**Comment by RuggedTime** [comment]
![image](https://github.com/NikitaCartes/EasyAuth/assets/46664847/32aa2928-2dd1-4fbf-aa9c-847a20be1361)
Well...not work

**Comment by NikitaCartes** [comment]
Will look into that, thanks

**Comment by RuggedTime** [comment]
Is it possible that it was caused by starting the server with root before?
I am using Ubuntu...But now the entire folder is onwed by accont "ubuntu", not "root"

**Comment by RuggedTime** [comment]
![image](https://github.com/NikitaCartes/EasyAuth/assets/46664847/501d7d14-098b-4415-943b-bbe5d9e2430b)
All the mod used, and I am using MCDReforged to start the server:
https://github.com/Fallen-Breath/MCDReforged

**Comment by NikitaCartes** [comment]
Auth list never worked correctly. Iirc it only shows cached players, after their log in, and resetting this list after server restart.

You can temporarily get right uuid using this site:
https://minecraft-serverlist.com/tools/offline-uuid
You need to use nicknames in lowercase, e.g. "nikitacartes" not "NikitaCartes"

**Comment by RuggedTime** [comment]
OHHH!   It works!  
Password updated successfully!
Thank you!   \(^o^)/~

**Comment by NikitaCartes** [comment]
You need to add %s in `offlineUuid` in config, so uuid will be shown in log
It will looks like that: "Offline UUID for %s is %s"

I fixed it in 3.0.0-16, but config will not update automatically.

**Comment by RuggedTime** [comment]
Problem solved!
