### ISSUE TITLE
Translation not working

### ISSUE THREAD

**Issue by xiaojuzi122** [NikitaCartes/EasyAuth#122]
The mod is not automatically translated into Chinese on the Chinese server, which is 1.20.4 and uses the latest mod version,I want to know why this is

**Comment by NikitaCartes** [comment]
EasyAuth sends messages depending on the language set in the client.
3.0.22 should support zh_ch and zh_tw languages.
What language do you use?

**Comment by xiaojuzi122** [comment]
zh_ch,But it doesn't work in the server
![Image_1706233790108](https://github.com/NikitaCartes/EasyAuth/assets/121807438/50a3b55a-6631-4070-be71-b8b20ace8f3e)

**Comment by xiaojuzi122** [comment]
I wonder if there can be a separate language setting,This situation should be much better

**Comment by NikitaCartes** [comment]
What version are you using?
In both 3.0.20 and 3.0.22 you can manually override messages in config.

You can find translation here:
https://github.com/NikitaCartes/EasyAuth/blob/fabric-1.20.4/src/main/resources/data/easyauth/lang/zh_cn.json

**Comment by xiaojuzi122** [comment]
mod version is 3.0.22,How should I manually overwrite it

**Comment by NikitaCartes** [comment]
You can find language config in `config/EasyAuth/translation.conf`

I will test translation on this weekend, maybe I can fix it.

**Comment by xiaojuzi122** [comment]
Just replace the code in this document with the code in the translated document, right？

**Comment by NikitaCartes** [comment]
No, 
```hocon
enter-password: {
	"text": "§6You need to enter your password!"
	"enabled": true
	"serverSide": true
}
enter-new-password: {
	"text": "§4You need to enter new password!"
	"enabled": true
	"serverSide": true
}
```

You need to replace "text" section with your message and set "serverSide" to false.
