### ISSUE TITLE
[FeatureReq] Option to disable cache

### ISSUE THREAD

**Issue by HyperPaint** [NikitaCartes/EasyAuth#123]
**Is your feature request related to a problem? Please describe.**

Hi. I was thinking about integrating the mod with WordPress (in theory, it is possible with any other system). Let me clarify that I use a MySQL database. The plan is as follows:
1. Password is changed on the website.
2. Hash (bcrypt) is written from the wp_users table to the easyauth table using a trigger in the database
3. You can log in to the game using a new password

In practice, it turned out that the mod uses invincible data caching, and there is no way to force it to reset the cache and re-read the database :(
Because of this, such a plan did not work

**Describe the solution you'd like**

It would be nice to have an option in the configuration that would disable the cache

useCache: false

Then the mod would access the database for the hash during authentication and after authentication would immediately write other information to the database: ip, was in portal, auth, etc...

**Describe alternatives you've considered**

As an alternative, I am currently considering such a plan
1. Password is changed on the website (wp_users)
2. Trigger records the changes in a separate table (account_history), where id, username, password, action (insert, update, delete), processed, insert timestamp, update timestamp are stored
3. Python script runs every minute (or less often) and gets all unprocessed records from the database
4. Script connects to the server via RCON, checks that the server is active and then performs the creation, updating and deletion of credentials through the mod commands

In fact, instead of updating the password in the database, I update it in the cache of mod

**Additional context**

I really hope to disable the cache, because this authentication mod is the only one suitable for fabric

**Comment by HyperPaint** [comment]
Alternative plan:
1. Password is changed on the website (wp_users)
1.1 Special plugin get plaintext when password created or changed

Terrible plan :(

**Comment by HyperPaint** [comment]
Plan is working

**Comment by HyperPaint** [comment]
Can you tell me if any modifications are planned according to the request?

**Comment by HyperPaint** [comment]
Can you tell me if any modifications are planned according to the request?

**Comment by NikitaCartes** [comment]
Yes, I'm planning to get rid of cache entirely, but I don't any ETA.
