### ISSUE TITLE
[BUG] I dont see my friends in the game after login and they dont see me too

### ISSUE THREAD

**Issue by Mrgaton** [NikitaCartes/EasyAuth#134]
easyauth-mc1.20-3.0.19.jar

The mods:

![image](https://github.com/NikitaCartes/EasyAuth/assets/68958481/7249be32-3470-456a-96e9-31fe114ff914)

**Comment by Mrgaton** [comment]
[config.json](https://github.com/NikitaCartes/EasyAuth/files/14642684/config.json)

**Comment by NikitaCartes** [comment]
Did you enable `hideUnauthenticatedPLayersFromPlayerList`?

Yes, you did

**Comment by Mrgaton** [comment]
but even after authenticate they seem like they arent on the server

**Comment by Mrgaton** [comment]
> Did you enable `hideUnauthenticatedPLayersFromPlayerList`?

yes it is

**Comment by Mrgaton** [comment]
so that may be the cause?

**Comment by Mrgaton** [comment]
ill try tomorow now its too late for me.

if it fixes i will close the issue if not i will try to send more info

**Comment by NikitaCartes** [comment]
Yeah, it caused this problem in the past
I thought it was fixed in 1.19.4 but apparently it won't

**Comment by Mrgaton** [comment]
Then why you dont put it on false by default

**Comment by NikitaCartes** [comment]
It's on false by default

**Comment by Mrgaton** [comment]
Ammm I don't remember touching that, sorry
