### ISSUE TITLE
[BUG] keep asking for Registration

### ISSUE THREAD

**Issue by HexHyte** [NikitaCartes/EasyAuth#14]
Nothing much to say, the problem started occurring after a EasyAuth reinstall.
Basically we can't login but only register again and again.
I've already tried removing the EasyAuth folder.
(I am on Fabric 0.7.4 for 1.17.1)

Any tips?

**Comment by NikitaCartes** [comment]
Which version of mod do you use, 1.9.7 or older?

If you use 1.9.7 please try with 1.9.6

Upd:
1) It asking for registration after relogin to server or server restart?
2) Version of Fabric API?
3) Did you change something in config?
4) Maybe some errors in console?

**Comment by HexHyte** [comment]
> Which version of mod do you use, 1.9.7 or older?
> 
> If you use 1.9.7 please try with 1.9.6
> 
> Upd:
> 
> 1. It asking for registration after relogin to server or server restart?
> 2. Version of Fabric API?
> 3. Did you change something in config?
> 4. Maybe some errors in console?

I tried with both 1.9.6 and 1.9.7 version.
1: It ask for registration after every relogin.
2: Fabric API is api-0.40.1+1.17.
3: I did a complete wipe of the EasyAuth folder.
4: No error in console by searching for "EasyAuth".

**Comment by NikitaCartes** [comment]
I don't thinks that's that matter, but:
Offline or online server? Linux or Windows? Other installed mods?

You can register user with command `auth register <uuid> <password>`, note that uuid must be for lowercase variant of nickname (e.g. `nikitacartes`, not `NikitaCartes`). You can use [that site](https://www.fabianwennink.nl/projects/OfflineUUID/) for offline uuid.

**Comment by HexHyte** [comment]
> I don't thinks that's that matter, but: Offline or online server? Linux or Windows? Other installed mods?
> 
The server is actually in Offline mode but it happens even when i use my main Mojang account. 
The host is running Linux. 
There are plenty of mods but the problem persist even when removing all the other mods.
I've also tried to remove the usercache.json file  but with no success.

**Comment by NikitaCartes** [comment]
@HexHyte 
Hello, sorry for long answer.

I'm finally can reproduce it and can suugest a quick fix for you:
Try to change `"useBCryptLibrary"` to true

**Comment by HexHyte** [comment]
> sorry for long answer.

Thanks for the answer man, don't worry about that

> I'm finally can reproduce it and can suugest a quick fix for you: Try to change `"useBCryptLibrary"` to true

This actually did the trick, thank you again!

**Comment by NikitaCartes** [comment]
@HexHyte 

I'm glad that help you.

> This actually did the trick, thank you again!

Be sure that you will not change back to `false` because players will not be able to log in after that
