### ISSUE TITLE
[BUG] offline player can't sent message.

### ISSUE THREAD

**Issue by AirJerryWhite** [NikitaCartes/EasyAuth#146]
**Versions**
* EasyAuth 3.0.20
* Fabric API 0.97.0+1.20.4

**Describe the bug**
offline player can't sent message.

server log:
 Failed to update secure chat state for abcdeFUCKU: 'Chat disabled due to missing profile public key. Please try reconnecting.'

**Comment by AirJerryWhite** [comment]
server mod list:
![A%@%96KCYHVE1)CQ6OAOU`J](https://github.com/NikitaCartes/EasyAuth/assets/55286554/a3cccef3-88d4-442e-825a-4a8ec04b5f42)

**Comment by NikitaCartes** [comment]
It's probably because you have `enforce-secure-profile` enabled in server.properties
