### ISSUE TITLE
fork for fabric servers, 1.20.6 (;

### ISSUE THREAD

**Issue by Legendmanj** [NikitaCartes/EasyAuth#150]
EasyAuth is only available for papermc servers

Would be actually good if fabric is introduced on this plugin!

If the support team sees this, please mind accepting my request as it's a great plugin to be used on small smps, if someone who's a member of this project can make a fork of it for fabric. Thank-you, and please mind doing it.

**Comment by NikitaCartes** [comment]
Wrong repo, you're already in Fabric mod

**Comment by Legendmanj** [comment]
> Wrong repo, you're already in Fabric mod

what do you mean? can i use it on fabric servers then?

**Comment by NikitaCartes** [comment]
@Legendmanj yes you can. But EasyAuth for Fabric has nothing to do with EasyAuth for Paper.
