### ISSUE TITLE
[BUG] Offline nickname support works only with nicknames that 6< letters long.

### ISSUE THREAD

**Issue by Misha4ek** [NikitaCartes/EasyAuth#161]
**Versions**
* EasyAuth 1.20.3-rc1-3.0.20
* Fabric API 0.95.1+1.20.4

**Describe the bug**
Whenever player with offline account tryes to join, they recive "lost connection: Failed to verify username!"
Only works with nicknames that <=5 letters long.
**To Reproduce**
1. Create offline account with nickname that is no longer than 5 letters.
2. Try to join offline server with mod on.
3. See error.

**Expected behavior**
Any nickname is sutable for joining.

**Additional context**
I host minecraft server on my pc. Before mod we had player with nick "ert" and after the mod I was forced to transfer all progress to another nickname that 7 letters long.

**Comment by NikitaCartes** [comment]
You can change regex that verifies usernames in config:

Default value: `^[a-zA-Z0-9_]{3,16}$`
Although it should allow players with >=3 symbols
