### ISSUE TITLE
[FeatureReq] Add MySQL support

### ISSUE THREAD

**Issue by nikijaz** [NikitaCartes/EasyAuth#17]
**Is your feature request related to a problem? Please describe.**
The problem is that a large number of mods use MySQL, and due to the lack of such an opportunity in EasyAuth, you have to set up new database using MongoDB.

**Describe the solution you'd like**
Support MySQL as database where everything will be stored.

**Comment by NikitaCartes** [comment]
It's already in [ToDo](https://github.com/NikitaCartes/EasyAuth/projects/1#card-65033336) and will be implemented together with SQLite support.

Hopefully I will be able to release it before 1.18
