### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Admany** [NikitaCartes/EasyAuth#173]
![image-31.png](https://github.com/user-attachments/assets/2e8c5a8b-3885-470d-b06d-6790a312ff22)

![Screenshot_20241113-153321_Chrome.jpg](https://github.com/user-attachments/assets/0a6599b9-5e16-4ebc-a096-3e965652fb80)

**Versions**
* EasyAuth 1.20.1
* Fabric API 1.20 1

**Describe the bug**
TRIGERED ANTIVIRUS AS AN TROJAN

**To Reproduce**
1. Go to the download page
2. Click on download easyauth 1.20.1
3. Download
4. Bitdefender instant notif that an trojan has been found

**Expected behavior**

**Additional context**

**Comment by NikitaCartes** [comment]
https://github.com/NikitaCartes/EasyAuth/issues/168#issuecomment-2430458199

**Comment by NikitaCartes** [comment]
and I upload new version at modrinth and curseforge
