### ISSUE TITLE
[BUG] Server crashes after a player registers

### ISSUE THREAD

**Issue by SiriusCel** [NikitaCartes/EasyAuth#176]
**Versions**
* EasyAuth 3.0.27
* Fabric API 0.110.0

**Describe the bug**
When a player enters and registers, their password the server shuts down

**To Reproduce**
1. Start the server
2. A player logs in
3. The player registers their password
4. The server will shut down after it is successfuly done.

**Expected behavior**
The player should be able to play and the server should've been able to run.

**Additional context**
Here is the log of the server from starting to its crash if that will help!

[serverlog.txt](https://github.com/user-attachments/files/17919037/serverlog.txt)

**Comment by NikitaCartes** [comment]
https://github.com/NikitaCartes/EasyAuth/wiki/GLIBC-problems
