### ISSUE TITLE
[FeatureReq] v2.0.4 1.17.1 on CurseForge please

### ISSUE THREAD

**Issue by jericjan** [NikitaCartes/EasyAuth#18]
**Is your feature request related to a problem? Please describe.**

I noticed that the mod on CurseForge has v2.0.4 for 1.18 but not one for 1.17.1.
I was using v1.9.7 and I couldn't get the `/auth register <uuid> <password>`  command to work so I was wondering maybe I needed an update for it to work. I was providing offline UUIDs so maybe that was the issue?

**Describe the solution you'd like**

Please upload version 2.0.4 of the 1.17.1 mod to CurseForge, and also fix `/auth register` if it actually doesn't work.

**Describe alternatives you've considered**

N/A

**Additional context**

I need it on CurseForge because I'm running my server on Aternos

**Comment by NikitaCartes** [comment]
Problem was discussed at Discord and closed in 2.0.5, thanks for report.
