### ISSUE TITLE
Server crash on startup (sometimes) Minecraft 1.18 EasyAuth 2.0.5

### ISSUE THREAD

**Issue by Carlosjrlu** [NikitaCartes/EasyAuth#21]
**Versions**
* Minecraft 1.18
* EasyAuth 2.0.5
* Fabric API 0.43.1

**Describe the bug**
Sometimes the server doesn't start. (Doesn't happen everytime)

**To Reproduce**
1. Start Server
2. See error

**Expected behavior**
The server should start always without errors

**Additional context**
Happens with the lastest artifact for 1.18 version 2.0.5 and with the alpha version on curseforge 2.0.4
[latest.log](https://github.com/NikitaCartes/EasyAuth/files/7629315/latest.log)

**Comment by Carlosjrlu** [comment]
May be something with the Fabric installer version lower than 0.10.0.

**Comment by NikitaCartes** [comment]
I'm trying to recreate it with installer 0.9.0 and loader 0.12.5, but unsuccessfully.
Mod shouldn't interfere with datafixers, this is very strange.

Do you use world from older version?

**Comment by Carlosjrlu** [comment]
No, newly generated world. Seems to happen from time to time, I really don't know why, that's why I said it could be a fabric problem, because I saw a similar problem on other mod's github.

**Comment by Carlosjrlu** [comment]
I've been trying to reproduce the bug again but seems to be gone with the change on the fabric installer.
