### ISSUE TITLE
Invisible Offline Players after server start or restart

### ISSUE THREAD

**Issue by Carlosjrlu** [NikitaCartes/EasyAuth#22]
**Versions**
* Minecraft 1.18
* EasyAuth 2.0.5
* Fabric API 0.43.1

**Describe the bug**
Offline players are invisible on first join after server start.

**To Reproduce**
1. Start Server
2. Join server with Premium Account
3. Join server with Offline Account and /login psswd
4. Premium player can't see offline player (invisible)
5. Disconnect offline player
6. Reconnect offline player
7. Premium player now can see offline player

Happens with both players being offline too

**Expected behavior**
Players should be able to see each other on first join

**Additional context**
This three images are in the same place and first connection of every player after server start
![2021-11-30_20 51 09](https://user-images.githubusercontent.com/20954701/144157721-02933bbf-38ca-45dd-a2bf-eee33e5eea22.png)
![2021-11-30_20 51 12](https://user-images.githubusercontent.com/20954701/144157743-c22a0596-f667-47aa-8d03-99c085bc1250.png)
![2021-11-30_20 51 14](https://user-images.githubusercontent.com/20954701/144157747-2da83a7f-9e3a-4ea0-acec-908ed64d0598.png)

**Comment by NikitaCartes** [comment]
Please check your `hideUnauthenticatedPLayersFromPlayerList` setting.

While in 1.17 it works fine, in 1.18 something changeв and that setting pretty unstable right now.

**Comment by Carlosjrlu** [comment]
Yeah, it seems that solved it.

**Comment by NikitaCartes** [comment]
I will temporarily disable that feature
