### ISSUE TITLE
Player is completely protected from damages and mobs after the login

### ISSUE THREAD

**Issue by parsampsh** [NikitaCartes/EasyAuth#23]
**Versions**
* EasyAuth 2.0.5
* Fabric API 0.44.0+1.18
* MineCraft 1.18.1

**Describe the bug**
Hi everyone. Today I and my friends were playing on our server which has your mod installed on it. After I logged in, I realized that I don't receive fall damage, hostile mobs don't attack to me, and it was looking like i am completely protected.
I did some researches and I saw other people had this problem. And I realized that it is because of a flag in playerdata named `invulnerable`. I don't know much about structure of your plugin and what it does in technical sense. But I can guess your plugin enables this flag (or something like that) before user login. Until user enters their password and log in, player is completely protected. They won't get damage, mobs won't attack to them and...
So what i guess is this: EasyAuth enables `invulnerable` flag on the player and after the login, it is supposed to disable the flag. But it doesn't do this sometimes. So player logs in but after that they are completely protected from any kind of danger.

**Comment by NikitaCartes** [comment]
I faced that problem several times too. 
Are you using premium account autologin? If you are, did this bug happens only with offline / online players or both?

**Comment by parsampsh** [comment]
> I faced that problem several times too. Are you using premium account autologin? If you are, did this bug happens only with offline / online players or both?

No i'm not using a premium account. Our server is on offline mode.

**Comment by NikitaCartes** [comment]
I suppose that `invulnerable=true` stay in that way after very unfortunate login/logout sequence.
So now that tag (with `invisible`) set to false after all types of successful login.

You can download it [here](https://github.com/NikitaCartes/EasyAuth/actions/runs/1613273632)

**Comment by parsampsh** [comment]
Thank you so much.
