### ISSUE TITLE
[BUG]Offline Player unable to connect with premiumAutologin enabled, 1.17.1

### ISSUE THREAD

**Issue by A-noximous** [NikitaCartes/EasyAuth#24]
**Versions**
* EasyAuth 2.0.5
* Fabric API 0.37.2

**Describe the bug**
When enabling premiumAutologin in the config file and online mode=true in the server.properties file, offlin mode players are unable to join and are kicked with the "Failed to verify username" error.

**To Reproduce**
1. enable premiumAutologin as per instructions on wiki
2. attempt to connect with an offline mode player
3. Scroll down to last 2 line in server log

**Expected behavior**
Player will be able to connect and will be prompted to login or register

**Additional context**
The offline player was created through the use of [mineflayer](https://github.com/PrismarineJS/mineflayer/), the same has not created any issues with regular offline mode servers.

**Comment by NikitaCartes** [comment]
That's happens probably because offline player use same nickname as someone other account. Add it (in lowercase) in `forcedOfflinePlayers` and `/auth reload`.
Or with `/auth addToForcedOffline <player>` in 2.0.6

**Comment by A-noximous** [comment]
Still results in the same error, the offline username in question does not have another account with the same name, confirmed with namemc.
Error:
`[12:43:13] [User Authenticator #3/ERROR]: Username 'ggeezz' tried to join with an invalid session
[12:43:13] [Server thread/INFO]: /127.0.0.1:57912 lost connection: Failed to verify username!`

Config file:
`"premiumAutologin": true,
    "forcedOfflinePlayers": [
      "ggeezz"
    ],`

**Comment by A-noximous** [comment]
Update: I had earlier accidentally tried to run premiumAutologin with online mode-false, so premiumAutologin was disabled when i fixed online mode, which resulted in the issue. It works as expected. Thanks for your time, and sorry for the mistake.
