### ISSUE TITLE
[BUG]The 'AutoLogin Mojang accounts' feature doesn't work as expected

### ISSUE THREAD

**Issue by doodlehuang** [NikitaCartes/EasyAuth#26]
**Versions**
* EasyAuth 2.0.5
* Fabric API 0.44.0

**Describe the bug**
Offline-mode Players cannot log into the server with [this config](https://github.com/NikitaCartes/EasyAuth/wiki/AutoLogin-Mojang-accounts) set.

**To Reproduce**
1. Install Fabric API and EasyAuth
2. Start the server once and then turn it off
3. Turn on AutoLogin as [this wiki page](https://github.com/NikitaCartes/EasyAuth/wiki/AutoLogin-Mojang-accounts) suggests, and set `online-mode=true` in server.properties
4. Start the server
5. See error (Premium players can join the server while offline-mode players see the 'Invalid Session' error.)

**Expected behavior**
Both premium players and offline-mode players can join the server with different login policies applied to them accordingly.

**Additional context**

**Comment by NikitaCartes** [comment]
That's happens probably because offline player use same nickname as someone other account. Add it (in lowercase) in `forcedOfflinePlayers` and `/auth reload`.
Or with `/auth addToForcedOffline <player>` in 2.0.6

// I'm definitely must update wiki pages and mention this moment

**Comment by doodlehuang** [comment]
The same happens even when we use random names that aren't occupied. Sometimes the error is shown as 'Failed to log in: null'
![image](https://user-images.githubusercontent.com/25525621/147380656-f6954315-de3e-46de-a47e-48f1f67ca76e.png)
Meanwhile, the console shows something like this:
![image](https://user-images.githubusercontent.com/25525621/147380670-9745a42b-9ce5-49a1-b5ef-d1fcd51a89c8.png)
And when I added a nickname in the `forcedOfflinePlayers`, the behavior now becomes more weird than before: An offline player with the added nickname can join in the server, but there will be no register or login process as if he has been authenticated.
It seems like the critical part of the authentication process is not working somehow.

**Comment by NikitaCartes** [comment]
Sorry for the long answer. I just didn't know what to say because I cannot reproduce this issue.

> An offline player with the added nickname can join in the server, but there will be no register or login process as if he has been authenticated.

There is probably because of that player still have valid session.

If you still encounter any problem feel free to reopen this issue or open new. I will answer faster next time
