### ISSUE TITLE
[BUG] Two folders are created for leveldbStore for seemingly no reason

### ISSUE THREAD

**Issue by were491** [NikitaCartes/EasyAuth#29]
**Versions**
* EasyAuth 2.0.6
* Fabric API 0.45.2

**Describe the bug**
When starting the server on Linux, two directories are created to store the auth database: leveldbStore and levelDBStore (note capitalization). The former seems to be always empty/unused, but it causes problems when trying to sync the server files to Windows.

**To Reproduce**
1. Install EasyAuth, ensuring that you are not using mongoDB

**Expected behavior**
As the leveldbStore folder seems entirely unused, it should not exist. If it is used, it should be a different folder name entirely rather than just a difference in capitalization (e.g., levelDBStore_temp)

**Additional context**
None. Maybe this causes issues for people on Windows using LevelDB? (seen some before)

**Comment by NikitaCartes** [comment]
~~I believe this is one more bug from levelDB itself~~ Okay, it was actually bug on my side, thanks for report.
Anyway I plan to move to SQLite as default DB in near future (with automated data migration of course).

@sdas-tech
It would be very cool if you can test your error (#6) with latest commit, I think it should fix your error.

**Comment by were491** [comment]
poggers

\*ahem* I meant "seems to work good for me"!
