### ISSUE TITLE
[BUG] Massive TPS drop on authentication

### ISSUE THREAD

**Issue by ghost** [NikitaCartes/EasyAuth#31]
**Versions**
* EasyAuth 2.0.5
* Fabric API 0.46.1

**Describe the bug**
TPS drops on authentication. https://spark.lucko.me/7XnvPpCw17

Can I do anything to make EasyAuth not cause lags? I am not running MongoDB or any other database, data stored on EasyAuth's own LevelDB. The performance was much higher when using AuthMe Reloaded or AmkMcAuth on Paper, however, I don't want to run Cardboard and Paper plugins on my server. The configuration is default except autologin for premium players.

1264 ms is plain ridiculous for automatic premium authentication. There are several more lag spikes on my server on auth event, I will be profiling further later.

Server configuration can be seen there: https://github.com/Euromance/ModdedFabricTechnicServer

**Comment by ghost** [comment]
Profile results suggest that the lag might be because of player protection on login event. https://spark.lucko.me/eElJLLkhnt

My guess is that server is waiting for these synchronous calls:

```
net.minecraft.server.PlayerManager.handler$onPlayerConnect()
xyz.nikitacartes.easyauth.event.AuthEventHandler.onPlayerJoin()
xyz.nikitacartes.easyauth.storage.PlayerCache.fromJson()
net.minecraft.entity.Entity.getBlockStateAtPos()
```

As these calls take enormous time to execute and make the whole server to hang during tick processing. Might make sense to save the player's state to in-memory cache, set the player's gamemode to `spectator` and only then do all these heavy tasks in a separate thread to recover the original player state after successful login.

**Comment by ghost** [comment]
`spark viewer` UI lets you search the trace for `EasyAuth` calls.

**Comment by ghost** [comment]
The second profiling was done with `premium auto-login` disabled, the first one with enabled. No difference, the same lag spikes.

**Comment by NikitaCartes** [comment]
I think lag spikes is due to chunk loading to check if player stand in Nether Portal.
![image](https://user-images.githubusercontent.com/18899227/150817780-4a83eb22-9d63-4922-8680-8ed871a77693.png)

https://github.com/NikitaCartes/EasyAuth/blob/b6f714a4bc49c9446a45048308f97e9c26660e0b/src/main/java/xyz/nikitacartes/easyauth/storage/PlayerCache.java#L101

Although it must happens only for first login for each offline player after restart

**Comment by ghost** [comment]
> I think lag spikes is due to chunk loading to check if player stand in Nether Portal

How can it take so long to check block ID of 8 blocks?

> Although it must happens only for first login for each offline player after restart

Indeed, no spikes on re-logs

**Comment by NikitaCartes** [comment]
> How can it take so long to check block ID of 8 blocks?

One block*.
It's Minecraft, I'm not suprised, lol.

I will try to move that check from main thread

**Comment by ghost** [comment]
Will be looking forward for updates! Not like this issue is a dealbreaker for me, just would be nice if there wasn't that spike.

Anyway, the mod is awesome, thank you and @samolego for your work, I love the premium auto-login feature!

**Comment by NikitaCartes** [comment]
I briefly tested it and seems like lag spike is negotiated.

Definitely should examine similar places in code in future.

**Comment by ghost** [comment]
Thank you for your time, will update ASAP!
