### ISSUE TITLE
Add auto login for Bedrock only account that login through Floodgate

### ISSUE THREAD

**Issue by M8torr** [NikitaCartes/EasyAuth#35]
Currently, auto login works in the below scenarios:

Scenario 1:
Login with Java account on a Java client

Scenario 2 (untested):
Login with Java account on a Bedrock client through Geyser

Scenario 3:
Login with Bedrock account, that is [globally linked](https://link.geysermc.org), on a Bedrock client through Geyser/Floodgate

It would be nice to have the below scenario working:

Scenario 4:
Login with Bedrock account, that is NOT linked with a Java account, on a Bedrock client through Geyser/Floodgate.

If scenario 4 would be implemented, please take considerations into not breaking scenario 3, since it is really helpful to keep using the same linked character using either Bedrock or Java accounts.

There is a Paper/Spigot plugin named [FastLogin](https://github.com/games647/FastLogin) that allows the above scenario that could be used as reference.
It would be really amazing if EasyAuth could have this functionality for Fabric.

Thanks,
M8torr

**Comment by NikitaCartes** [comment]
Closed with #49
Feel free to reopen if case of something
