### ISSUE TITLE
[BUG] Crash while sleeping in bed with `premiumAutologin` set to true

### ISSUE THREAD

**Issue by kotx** [NikitaCartes/EasyAuth#4]
**Versions**
* EasyAuth 1.9.3
* Fabric API 0.37.0

**Describe the bug**
When right-clicking (sleeping) on a bed client-side, the mod crashes

**To Reproduce**
1. Install EasyAuth on client
2. Click on bed

**Expected behavior**
Player sleeps in bed

**Comment by NikitaCartes** [comment]
I will probably fix it tomorrow, but why do you need this mod client-side?

**Comment by kotx** [comment]
> I will probably fix it tomorrow, but why do you need this mod client-side?

To be honest I'm just too lazy to synchronize two modpacks for the client and server.

**Comment by NikitaCartes** [comment]
Fair enough.
From 1.9.4 mod will run only on server and won't do anything on client.
