### ISSUE TITLE
[FeatureReq] premiumAutologin for geyser

### ISSUE THREAD

**Issue by dmunozv04** [NikitaCartes/EasyAuth#44]
**Is your feature request related to a problem? Please describe.**
It's inconvenient for bedrock users to have to authenticate when floodgate and geyser are already checking their auth.

**Describe the solution you'd like**
Allow bedrock clients to skip the login process

**Describe alternatives you've considered**
- Leaving it as it is (making bedrock clients login)

**Additional context**
Floodgate connections are seen as lan connections eg: 192.168.1.3. Maybe a lanAutologin option could solve the issue in a simpler way

**Comment by dmunozv04** [comment]
Would you mind if I make a PR implementing `floodgateAutologin` using the [floodgate API](https://wiki.geysermc.org/floodgate/api/)?

**Comment by NikitaCartes** [comment]
It would be cool if you do it
