### ISSUE TITLE
Softlock when disconnecting inside of a nether portal

### ISSUE THREAD

**Issue by booleancoercion** [NikitaCartes/EasyAuth#48]
If you happen to disconnect from the server while stuck inside a portal (e.g. when struck by poor internet), you can get softlocked, as the chat is not available while inside the portal and as such you cannot use it to log in with your password. This is very frustrating, especially since you need someone else to come and remove the portal for you.

The way I see it, there's two possible fixes:
1. Destroy the portal that the player might be standing in.
2. Teleport the player momentarily to a dummy location so that they can input their credentials, and then place them back in the original spot when they've done so.

If these are considered too disruptive, consider adding a configuration option to enable one of them, or a different solution entirely.

**Comment by NikitaCartes** [comment]
It already should try to rescue players from portal.
I will check that
https://github.com/NikitaCartes/EasyAuth/blob/a5c796ffeff3a09066d8fce3a1f115e49a29bfd5/src/main/java/xyz/nikitacartes/easyauth/event/AuthEventHandler.java#L112

**Comment by NikitaCartes** [comment]
It already should try to rescue players from portal.
I will check that
https://github.com/NikitaCartes/EasyAuth/blob/a5c796ffeff3a09066d8fce3a1f115e49a29bfd5/src/main/java/xyz/nikitacartes/easyauth/event/AuthEventHandler.java#L112-L125
