### ISSUE TITLE
[BUG] Sometimes online player treated as offline player

### ISSUE THREAD

**Issue by EnderGirl1500** [NikitaCartes/EasyAuth#51]
**Versions**
* EasyAuth 3.0.0
* Fabric API 0.47.10

**Describe the bug**
After creating this "mixed" offline-online mode, the inventory of my players disappeared. I'll do more research to see if it happened on everyone or just premium accounts. Also, other data like location and homes will be lost.

**To Reproduce**
1. Set the EasyAuth config to default, and the server to offline mode.
2. Enter the server and put something in your inventory.
3. Stop the server, then create the mixed mode.
4. Start the server and enter. You'll be in the spawn with no items at all.

**Expected behavior**
I guess everybody should have their inventories after making this changes.

**Comment by TechPro424** [comment]
This is a known issue. Check https://github.com/NikitaCartes/EasyAuth/wiki/AutoLogin-Mojang-accounts

**Comment by NikitaCartes** [comment]
As I understand you moved from fully offline mode to mixed mode? In that case all advancements, playerdata **should** be  migrated automatical for all players, both offline and online.

If you move back to offline from online mode items (and other things) will be lost. (You can rename files that contain that information by hands)

**Comment by EnderGirl1500** [comment]
Well is there any solution after all items being lost?

**Comment by EnderGirl1500** [comment]
I entered the playerdata folder but everything is encrypted

**Comment by NikitaCartes** [comment]
You can rename files in world/playerdata, world/stats and world/advancement.
They use uuid of player as their name, so you need to change that. You can use https://minecraft-serverlist.com/tools/offline-uuid for offline uuid and https://namemc.com/ for online uuid.

**Comment by EnderGirl1500** [comment]
Some of my players cant join the server, how can I fix that aswell?

**Comment by NikitaCartes** [comment]
What type of error they get?

**Comment by EnderGirl1500** [comment]
Before forcing their offline-uuid they got something like invalid player data, and after doing so they just get disconnected

**Comment by NikitaCartes** [comment]
Something useful in logs?

**Comment by EnderGirl1500** [comment]
I don't think so, but here's the lastest log
[latest.log](https://github.com/NikitaCartes/EasyAuth/files/8961221/latest.log)

**Comment by NikitaCartes** [comment]
Check your `config.worldSpawn.dimension` setting or set spawn via [command](https://github.com/NikitaCartes/EasyAuth/wiki/Coordinate-Hiding)

**Comment by EnderGirl1500** [comment]
Did it

**Comment by NikitaCartes** [comment]
Does it help after restart?

**Comment by EnderGirl1500** [comment]
A different person tried to join and he couldn't aswell
[latest.log](https://github.com/NikitaCartes/EasyAuth/files/8961523/latest.log)

**Comment by NikitaCartes** [comment]
Can you send server.properties and mod's config?

**Comment by EnderGirl1500** [comment]
[config.zip](https://github.com/NikitaCartes/EasyAuth/files/8961653/config.zip)

**Comment by NikitaCartes** [comment]
It's seems like that player tries to connect with offline account but this name is used in someone's else online account. You can add it in forcedOfflinePlayers with `auth addToForcedOffline <player>`

**Comment by EnderGirl1500** [comment]
I did it with one of the players but it didn't work

**Comment by EnderGirl1500** [comment]
I just did it with someone else and worked, how can i fix it for the ones that cant join even with the force offline?

**Comment by EnderGirl1500** [comment]
Today I made no changes and someone who played like 3h ago has lost the inventory

**Comment by NikitaCartes** [comment]
Sometimes online player treated as offline player, this known  rare bug. I will look into that in next week, but for now server restart should help

**Comment by EnderGirl1500** [comment]
ok and what about those who cant join at all? One tried changing the username into one that isnt occupied and it didnt work

**Comment by NikitaCartes** [comment]
So one more time:
It's offline player;
This nickname doesn't belongs to someone's else online account (or this player in forced offline list);
There is no any error in logs?

Can you join in Discord server, I think it would be easier?
https://discord.gg/UY4nhvUzaK

**Comment by EnderGirl1500** [comment]
Its offline player, his nickname doesnt belong to anyone and even when forcing him on the list it doesnt work. Imma join now.

**Comment by TechPro424** [comment]
Yes the same thing is happening to me as well
offline player;
the player is in forcedoffline list

there is some red thing related to easyauth in the logs, idk what it means tho 
it is the same error that EnderGirl got
https://mclo.gs/gw4E4cq

**Comment by TechPro424** [comment]
I fixed the problem
I had to go to spawn and use the `auth SetSpawn` command because spawn dimension was null in config
@EnderGirl1500 maybe it might work for you?

**Comment by Glaived** [comment]
> I fixed the problem I had to go to spawn and use the `auth SetSpawn` command because spawn dimension was null in config

https://github.com/NikitaCartes/EasyAuth/blob/4a15a7223037e64e5cbfff0035c6213288150018/src/main/java/xyz/nikitacartes/easyauth/storage/AuthConfig.java#L252

I am not a Java developer, but this should solve the problem:
```java
public String dimension = "minecraft:overworld";
```
