### ISSUE TITLE
[BUG] Use commands while not logged/registered

### ISSUE THREAD

**Issue by AppleInTheSky** [NikitaCartes/EasyAuth#56]
**Versions**
* easyauth-mc1.17.1-2.0.5
* fabric-api-0.46.1+1.17

**Describe the bug**
You can use some commands while you are not logged, for example, luckperms
![image](https://user-images.githubusercontent.com/101140963/178133801-d036a15c-43e0-43af-b8b5-1a37b4945d29.png)
(Sorry for spanish)

**Expected behavior**
Not used the command, as the other commands in vanilla

**Comment by NikitaCartes** [comment]
Quick question — are you using Cardboard?

**Comment by AppleInTheSky** [comment]
Nope
