### ISSUE TITLE
[BUG] spawnOnJoin causing everlasting "Loading Terrain" for Java Edition players

### ISSUE THREAD

**Issue by shizotoaster** [NikitaCartes/EasyAuth#58]
**Versions**
* EasyAuth mc1.19-3.0.0-7
* Fabric API 0.58.0+1.19

**Describe the bug**
For Java Edition it's just everlasting loading screen, for Bedrock Edition (Geyser) players it's empty world with no blocks at all

**To Reproduce**
1. Turn "spawnOnJoin" on in mod config
2. Try to connect the server

**Additional context**

**Comment by stinkysmellystinkysmelly** [comment]
Setting config option "allowMovement" to true seems to fix this bug. Perhaps the client is waiting for movement before clearing the loading terrain screen when you join a server?

**Comment by jiriks74** [comment]
Same issue here. Temporarily resolved by allowing movement or turning off spawn on join.

`"spawnOnJoin": false,`
`"allowMovement": false,`

**OR**

`"spawnOnJoin": true,`
`"allowMovement": true,`
