### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Tresillo2017** [NikitaCartes/EasyAuth#59]
**Versions**
* EasyAuth 3.0.0-8
* Fabric API 0.58.5

**Describe the bug**
Every time I set forcepremiumautologin to true, it change backs to false

**To Reproduce**
1. Go to 'to the config'
2. Click on 'change premiumautologin to true'

**Expected behavior**
Not to change back to false.

**Additional context**
I'm using minecraft 1.19.1 fabric server

**Comment by NikitaCartes** [comment]
You also need to enable `online-mode=true` in `server.properties` (offline player still can join with it)
