### ISSUE TITLE
[BUG] players lose all progress when downloading on an existing server.

### ISSUE THREAD

**Issue by LazyGamer1111** [NikitaCartes/EasyAuth#60]
**Versions**
* EasyAuth 3.0.0-7
* Fabric API 0.58.0+1.19

**Describe the bug**
When players logged in on an existing server, all their progress got reset.

**To Reproduce**
1. install the mod on an existing server with a playerbase.
2. Log in
3. See how all progress is lost.

**Expected behavior**
People would spawn at the correct location with the inventory they had.

**Comment by NikitaCartes** [comment]
You can restore that data by renaming files in folders PlayerData, achievements and stats from old uuid to new uuid.

**Comment by LazyGamer1111** [comment]
> You can restore that data by renaming files in folders PlayerData, achievements and stars from old uuid to new uuid.

alright, thanks!

I'll try it!
