### ISSUE TITLE
[BUG]Can't add forced-offline player

### ISSUE THREAD

**Issue by solitary-sails** [NikitaCartes/EasyAuth#61]
**Versions**
* EasyAuth 2.0.5
* Fabric API 0.46.1

**Describe the bug**
Unable to use this command: /auth addToForcedOffline <player>

_online-mode_ in server.properties and _premiumAutologin_ in Eaeyauth config file have both been set to _true_.
I tried to add a forced offline player using my admin account, but I couldn't execute the corresponding command.

**Additional context**
Other mod used on the server：
![image](https://user-images.githubusercontent.com/52939914/192075296-e01a622c-8815-4830-a6a1-f6b9676b42ac.png)
Screenshot of the problem:
![image](https://user-images.githubusercontent.com/52939914/192075346-5359701e-6ad9-4c3e-9a69-ff106a986bba.png)

**Comment by NikitaCartes** [comment]
This command was added in later version, you can add player manually in config (in lower case)

**Comment by solitary-sails** [comment]
No wonder! Perhaps you can mark this in the wiki.
