### ISSUE TITLE
[BUG] Changing "lang" part of config.json apparently has no effect.

### ISSUE THREAD

**Issue by FaustHeinrich** [NikitaCartes/EasyAuth#63]
**Versions**
* EasyAuth 3.0.0-8 
* Fabric API 0.62.0

**Off-Topic**
Thank you for updating this mod to 1.19! I use it to run a non-whitelist server, which is protected by a global password. I find it easier to distribute a password to my friends, than to whitelist every single player.

**Describe the bug**
I Changed these Strings in config.json:
```
"lang": {
	"loginRequired":"Some Message 1",
	"notAuthenticated": "Some Message 2",
}
```
But ingame, upon login, the default messages are displayed in Chat:
```
You are not authenticated!
Try with /login, /l to authenticate!
```

Does not change after `/auth reload` or server restart.

**To Reproduce**
1. Change strings in config.json
2. Reload config `/auth reload` or restart server.
3. Log into server with unauthenticated user.
4. Read Prompt in the Chat.

**Expected behavior**
Ingame Prompts change to strings from config file.

**Comment by NikitaCartes** [comment]
Disable `enableServerSideTranslation`

**Comment by FaustHeinrich** [comment]
Works. Thank You!
