### ISSUE TITLE
[FeatureReq] Config files in config folder

### ISSUE THREAD

**Issue by luishfonseca** [NikitaCartes/EasyAuth#64]
**Is your feature request related to a problem? Please describe.**
I deploy my minecraft servers with [NixOS](https://github.com/Infinidoge/nix-minecraft), that turns my mods folder into a read-only symlink.
EasyAuth fails when trying to create the ./mods/EasyAuth/ folder

**Describe the solution you'd like**
Optionally allow for the config files to be stored on ./config/EasyAuth/

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by NikitaCartes** [comment]
Fixed in 3.0.21

**Comment by NikitaCartes** [comment]
Database still in mods/EasyAuth, but i will move it in future with support for SQLite
