### ISSUE TITLE
[BUG]requires players to regiser after restart the server

### ISSUE THREAD

**Issue by lonelysam3** [NikitaCartes/EasyAuth#65]
my players don't want to lose their data when i close my server. can you add it?

**Comment by NikitaCartes** [comment]
How do you stop your server?
`stop` command should work fine.
And you can try `save-all`

**Comment by lonelysam3** [comment]
the server will crash,and someone will steal op's account after i restart the server

**Comment by NikitaCartes** [comment]
Yes, after crash data is not saves right now

**Comment by lonelysam3** [comment]
so can you help me to save my players' data after crash?

**Comment by Bugstudios** [comment]
i agree with this :D thank you soooo much i am a member of lonelysam3's server

**Comment by lonelysam3** [comment]
someone will steal op's account and damage other players' buildings. i don't want this situation happens.

**Comment by KUBOAKI01** [comment]
fu town think,e......you should try to solve it

**Comment by NikitaCartes** [comment]
I said that you can save data by proper stopping server/save-all command. Also you can restart server after all ops regisered.

**Comment by KUBOAKI01** [comment]
fine

**Comment by nikijaz** [comment]
> someone will steal op's account and damage other players' buildings. i don't want this situation happens.

It is enough to stop the server once to successfully save the entered data. If the server crashes constantly, then you should first find the cause of the crash, but in the meantime, the mod works as intended.

**Comment by lonelysam3** [comment]
it doesn't work
even if i stop the server properly,the data still lost.
i just test if i don't use any other mods and stop the server normally.

**Comment by KUBOAKI01** [comment]
we didn't restart it,but it still lost the data

**Comment by NikitaCartes** [comment]
Does it say something in log?

**Comment by KUBOAKI01** [comment]
no

**Comment by NikitaCartes** [comment]
Can you send full log (you can delete ips and other private info)? You can send it in Discord

**Comment by lonelysam3** [comment]
ok,after a month of testing,i found these questions:
1.the mod will require players to regiser after restarting the server even though they had already regisered before the server restarted.
2.lauguage will change to English in bedrock edition,but in java edition the lauguage is Chinese.

**Comment by lonelysam3** [comment]
@NikitaCartes will you fix these questions?

**Comment by NikitaCartes** [comment]
Autosaving was added in 3.0.0-14
