### ISSUE TITLE
[BUG]无效的玩家数据(invalid player data)

### ISSUE THREAD

**Issue by lonelysam3** [NikitaCartes/EasyAuth#77]
**Versions**
* EasyAuth 3.0.0-11
* Fabric API 0.69.1

**Describe the bug**
当服务器版本从1.19.2升级到1.19.3时，已注册玩家无法进入游戏，会出现无效的玩家数据
When I update my server from 1.19.2 to 1.19.3,the player that had registered can't join the server,the error is invalid player data.

(如果可以，请使用中文回复)

**To Reproduce**
1.update the server to 1.19.3
2.delete other mods except EasyAuth and Fabric API
3. start the server

**Expected behavior**
所有玩家都可以加入服务器
All players can join the server.

(如果可以，请使用中文回复)

**Additional context**
当我移除EasyAuth文件夹时错误消失，但玩家数据全部消失了
When I remove EasyAuth folder,the error disappered.but all player's data lost.

**Comment by NikitaCartes** [comment]
Can't reproduce it.
Can you send error from log?

And I don't think that data can be recovered.

**Comment by lonelysam3** [comment]
the log had lost.
And sometimes the error will happen in 1.19.2
there is some screenshots:
![5FT)YLXRQRAM@L3))EI{HO6](https://user-images.githubusercontent.com/109451881/210158343-e637e417-a3a3-42bb-a1f3-c0423f1ef49f.png)

![F$L ACZD8J~08K%C%CV{(O6](https://user-images.githubusercontent.com/109451881/210158380-165198f6-cf32-402e-96d3-76eff463e501.png)

![{U%)M $9ODGS_X~K(4{LZG5](https://user-images.githubusercontent.com/109451881/210158389-9d732e04-3115-4069-9141-414a2ed6d218.png)

**Comment by lonelysam3** [comment]
you can try update the server and the easyauth mod(use fabric installer to overlay Installation) to reproduce the error.

**Comment by lonelysam3** [comment]
I had fix this error. sorry for waste your time.
