### ISSUE TITLE
[BUG] Packets exchanged between client and server shoot up to 3000+ during login/register

### ISSUE THREAD

**Issue by saransh323** [NikitaCartes/EasyAuth#8]
**Versions**
* EasyAuth 1.9.3
* Fabric API 0.37.1

**Describe the bug**
When a player joins the server and is in the frozen state where he is asked to login/register, the packets exchanged between the client and the server (tx and xx on left side in F3 debug screen) steadily rise to more than 3000, before the player is disconnected for not entering the password in time (This number may increase if the time limit is increased).

**To Reproduce**
1. Install EasyAuth on the server.
2. Start the server.
3. Join the server, but don't login/register.
4. Open the debug screen with F3.
5. Observe the "tx" and "rx" values go to ridiculous amounts (usually, they are at 20-30).

Screenshot: ![2021-07-27_15 05 10](https://user-images.githubusercontent.com/24824351/127183907-516c676a-8381-44c1-89bf-21ef5dc87e78.png)

**Expected behavior**
The packets exchanged should be normal, rather than increasing with time.

**Additional context**
An increased number of packets being exchanged means that it is impossible to have EasyAuth on the server and implement a reasonable rate-limit from server.properties at the same time.

A higher rate of packet exchange may also require a lot of internet bandwidth, but I cannot confirm whether the packets transferred actually carry enough information to have an impact on network usage.

**Comment by NikitaCartes** [comment]
Thanks for the report!

I'll try to figure it out.
But I'm not sure if I can fix this problem because of the way how packet (movement in particular) cancellation works.

**Comment by saransh323** [comment]
Ok, cool! 

I forgot to mention another thing: the increased packets cause you to get kicked form the server in 5-6 seconds if you are in spectator mode, because, apparently, the packet rate limit for spectator mode is 600 or something.

**Comment by NikitaCartes** [comment]
I added new settings in experimental part which limit how often server can send teleportation packet to unauthorized players.

Note that this settings is server-wide so maximum rate would be (1000/teleportationTimeoutInMs) per seconds for all unauthorized players. I don't think it cause any problem until you will have something like few hundreds unauthorized players at the same moment.

Value 0 would effectively disable this settings so players will be teleported after each packet.

By default value is 5, so it will be capped at 200 packets/second.

If you want you can test pre-release version with this settings. You can download it [here](https://github.com/NikitaCartes/EasyAuth/runs/3186039564) (click at `Artifacts` button)

**Comment by saransh323** [comment]
Thanks a lot!
