### ISSUE TITLE
[FeatureReq] Add Support When Use Geyser

### ISSUE THREAD

**Issue by MyBlueHorizon** [NikitaCartes/EasyAuth#80]
My server use EasyAuth with Geyser. I set server's online-mode to true and enable premiumAutologin.
However, When I try to login in by Geyser, I was inform that I need a online mode account.
Form the wiki, the EasyAuth already create a "mixed" online mode server, but it seem not work well with Geyser

**Comment by TechPro424** [comment]
add floodgate to your server and enable the floodgateAutoLogin and premiumAutoLogin option in config
and set online-mode to true in server.properties
