### ISSUE TITLE
[BUG] EasyAuth crashes the server when using Create's Deployer block

### ISSUE THREAD

**Issue by mikurei** [NikitaCartes/EasyAuth#87]
**Versions**
* EasyAuth mc1.19.1-3.0.0-8
* Fabric API 0.76.0+1.19.2
* Create 0.5.0.i-961+1.19.2

**Describe the bug**
Server crash when using the Deployer from Create (caused by easyauth validation)

**To Reproduce**
1. Spawn the deployer item
2. Put it on the ground
3. Connect the creative motor to it
4. It will crash

**Expected behavior**
It shouldn't crash, user is authenticated

**Additional context**
Attaching the crash report
[crash-2023-04-09_02.19.37-server.txt](https://github.com/NikitaCartes/EasyAuth/files/11184447/crash-2023-04-09_02.19.37-server.txt)

**Comment by NikitaCartes** [comment]
It was fixed in 3.0.0-14 version.

**Comment by mikurei** [comment]
Oh, my bad! Thanks for the quick response :) I guess the issue can be closed.
