### ISSUE TITLE
Auth uuid is blank in server log

### ISSUE THREAD

**Issue by ProxtosScorn** [NikitaCartes/EasyAuth#88]
1.18.2

when i try to login with my password it says wrong password and kicks me off the server. when i use /register to enter a new password it says that i am authenticated but still continues to send "you are not authenticated" messages and my new password does not work at all. when i use /auth to update my password it says that i am not registered. i use /auth register to register myself (i am op) and updates my playerdata. however when i use auth list i do not show up in it and although /auth update is now working on console when i try to login on client it still says wrong password. i am unable to find the config file for easyauth in my server files.

**Comment by NikitaCartes** [comment]
Config is in mods/EasyAuth.
Can you send list of your mods just in case?

**Comment by ProxtosScorn** [comment]
i found the config file. however it seems that there isn't a file storing the passwords of players. to be clear, it used to work before i forgot mine. this is why i tried to reset the password, but to no avail.
mods:
42 in total
advanced-nbt-tooltip-1.7.0-1.18.jar

All Arrows Infinity Fix-FABRIC-1.0.0-MC-1.18.jar

anti-xray-1.2.1-Fabric-1.18.2.jar

antishulkerdupe-1.0.0.jar

architectury-4.5.76-fabric.jar

betterthanmending-1.3.0.jar

Bookshelf-Fabric-1.18.2-13.2.20.jar

BowInfinityFix-1.18.x-fabric-rv11.jar
chestcavity-2.16.2.jar

cloth-config-6.2.57-fabric.jar

cmdkeybind-1.5.4-1.18.jar

collective-fabric-1.18.x-4.27.jar

deathbackup-fabric_1.18.x-1.5.jar


easyauth-mc1.18.2-3.0.0-6.jar

enchantingcommands-fabric_1.18.x-2.1.jar

essential_commands-0.23.0-mc1.18.2.jar

expanded-armor-enchanting-1.0.2.jar

expanded-axe-enchanting-1.0.3.jar

expanded-trident-enchanting-1.0.3.jar

expanded-weapon-enchanting-1.0.2.jar

fabric-api-0.53.4+1.18.2.jar

fabric-language-kotlin-1.8.0+kotlin.1.7.0.jar

ftb-library-fabric-1802.3.6-build.123.jar
ftb-ranks-fabric-1802.1.8-build.34.jar

GamemodeOverhaul-1.1.1.jar

grind-enchantments-1.6.4+1.18.2.jar

inventorio-1.18-fabric-1.7.0.jar

InvView-1.4.8-1.18+.jar

justmobheads-fabric_1.18.x-5.4.jar

justplayerheads-fabric_1.18.x-1.8.jar

KeepHeadNames-1.5.1-fabric-1.18.jar

ledger-1.2.4.jar

logprot-fabric-1.18-1.6.jar


LuckPerms-Fabric-5.4.25.jar

MoreCommands-3.10.1_1.16.4-22w16b.jar

Real-Inf-Bow-1.1.0-1.18.1.jar

servertick-mc1.18-1.6.jar

skin-restorer-1.0.4.jar

tatercart-1.0.0-pre.4+1.18.2.jar

teams-2.0.1-b2.jar

troll-commands-1.1.1.jar

worldedit-mod-7.2.10.jar

**Comment by ProxtosScorn** [comment]
how do i fix this issue

**Comment by NikitaCartes** [comment]
I think you updated password for wrong uuid. It's a bit confusing right now and will be changed in future.

In command as `auth update <uuid> <password>` you should use uuid for lower-case version of your name. You can get it with command `auth uuid <nickname>` or with [this site](https://minecraft-serverlist.com/tools/offline-uuid).

Also I would recommend to update to [newer release](https://github.com/NikitaCartes/EasyAuth/releases/tag/3.0.0-14)

**Comment by ProxtosScorn** [comment]
i have tried the auth update command, it just returns a blank behind the player name. as for why i haven't updated to the newer release, it is because my server is currently running on 1.18.2.

**Comment by NikitaCartes** [comment]
3.0.0-14 supports 1.18.2 too.

Can you send what exactly command do you type and your nickname? You can do it in Discord dm if you want.

**Comment by NikitaCartes** [comment]
Can you try `auth update 6d35102e-f09b-38f4-835c-1af4d065dc3d <new_password>`?

**Comment by ProxtosScorn** [comment]
thank you, it works! how do i get the uuid?

**Comment by NikitaCartes** [comment]
With site that I posted before.

**Comment by ProxtosScorn** [comment]
thanks. i will let you know if there are any other problems
