### ISSUE TITLE
[BUG] Text tip lost

### ISSUE THREAD

**Issue by RuggedTime** [NikitaCartes/EasyAuth#91]
**Versions**
* EasyAuth ：easyauth-mc1.19.4-3.0.0-15
* Fabric API ： fabric-api-0.76.0+1.19.4

**Describe the bug**
![image](https://user-images.githubusercontent.com/46664847/235887198-f154ae5e-d816-4d8a-8834-31658850de7d.png)

This is my config file
![image](https://user-images.githubusercontent.com/46664847/235886634-89dfca13-1bcc-4689-9273-c1d9e8aad0ff.png)

This bug occurs constantly

**Comment by NikitaCartes** [comment]
Disable server-side translation on config file

**Comment by NikitaCartes** [comment]
Which language do you use in your client?

**Comment by RuggedTime** [comment]
>Chinese， zh_CN

**Comment by RuggedTime** [comment]
So should I change "enableServerSideTranslation" to false?

**Comment by NikitaCartes** [comment]
Yes, it will help.

Can you please send me list of your client mod? You can do it in Discord DM.

**Comment by RuggedTime** [comment]
Actually, I am using none client mod. 
I just launch minecraft with MultiMC and then enter the server.
