### ISSUE TITLE
[BUG]premiumAutoLogin can't work at 3.0.0-17

### ISSUE THREAD

**Issue by MyBlueHorizon** [NikitaCartes/EasyAuth#94]
**Versions**
1.20
* EasyAuth X.Y.Z
3.0.0-17
* Fabric API X.Y.Z
0.83.0

**Describe the bug**
[EasyAuth]: With online-mode enabled and premiumAutoLogin disabled, offline players will not be able to join.
but I already set it to "true"

**To Reproduce**
just start server twice, and the bug will appear.

**Expected behavior**
premiumAutoLogin work

**Additional context**
none

**Comment by NikitaCartes** [comment]
It was wrong log messages. Fixed in https://github.com/NikitaCartes/EasyAuth/commit/2d6de9e6cc2e22d7aaf9c1bae2e49d6a9d4b7baa.

EasyAuth should work normally even with that message, but you can re-download 3.0.0-17 version, I replaced it with fixed message.
