### ISSUE TITLE
[CRITICAL BUG] When logging in or registering the command with a password gets sent to chat

### ISSUE THREAD

**Issue by jamieroot** [NikitaCartes/EasyAuth#95]
**Versions**
* EasyAuth 3.0.0-17
* Fabric API 0.83.1+1.20.1

**Describe the bug**
When our server updated to 1.20.1 and we needed to register, EasyAuth would just send the full command to chat and it would be seen by everyone online. For example: <edlt_> /l imeditlmao

**To Reproduce**
1. Register/Login with your password
2. Command gets sent to chat

**Expected behavior**
Upon logging in or registering, the command shouldn't get sent in chat and you should register normally.

**Additional context**
It gets worse with a Discord chat mod, for example Simple Discord Link, because it gets sent to a Discord chat.

**Comment by NikitaCartes** [comment]
Can't recreate it.

Maybe some specific mod that interact with chat in wrong way?
Can you send list of mods?

**Comment by jamieroot** [comment]
MCDiscord Chat is the only mod that interacts with chat in some way. The other mods that we have are AntiXray, Lithium, SkinRestorer, Starlight and Simple Voice Chat

**Comment by NikitaCartes** [comment]
Can you check it without other mods (except for Lithium/Starlight) or send me server zip (configs and mods) in Discord?

**Comment by jamieroot** [comment]
I'll send you configs and mods on Discord when I'm gonna be home

**Comment by jamieroot** [comment]
Sorry, the issue is not related with the mod. The issue persists even after removing the mod. Probably something with MCDiscord.

**Comment by jamieroot** [comment]
Yup, it was MCDiscord. The default config allows for any commands to get broadcasted to chat

**Comment by NikitaCartes** [comment]
Strange default behavior. Glad that you resolved this issue.
