### ISSUE TITLE
[FeatureReq] Geyser compatibility

### ISSUE THREAD

**Issue by timtijmen2** [NikitaCartes/EasyAuth#96]
Hey, i want to allow cracked players on the server but we are also using geyser but when they try to join they get stuck and are told to login.

Is there a way to set it up so those who are already authanticated by gesyer and floodagate to join without loggining in?

**Comment by NikitaCartes** [comment]
`floodgateAutoLogin` should work

**Comment by timtijmen2** [comment]
Oh sweet, thanks
