### ISSUE TITLE
[FeatureReq] use online uuid for online players

### ISSUE THREAD

**Issue by CapnCranch** [NikitaCartes/EasyAuth#98]
**Is your feature request related to a problem? Please describe.**
Its hard to add this to an existing server because of the people who have already been playing. Since when you rejoin after offline is enabled it doesnt have your inventory or anything.
**Describe the solution you'd like**
A way to have uuids for online players link with offline uuid so they can have their skins and inventories will remain.

**Comment by NikitaCartes** [comment]
Online players with online uuid should already be possible with
https://github.com/NikitaCartes/EasyAuth/wiki/AutoLogin-Mojang-accounts

**Comment by NikitaCartes** [comment]
If it's not that you want and I misunderstood you, feel free to reopen this issue.
