### ISSUE TITLE
[BUG] Server kicks out everyone with "Chat Validation Mesage Failure" error after new player tries to chat

### ISSUE THREAD

**Issue by GitHubbingOuttaHere** [NikitaCartes/EasyAuth#99]
**Versions**
* EasyAuth 3.0.0-17
* Fabric API 0.84.0+1.20.1

**Describe the bug**
When there is at least one player in the server, then another joins, when the newly joined player tries to send a message, the server kicks out everyone, with the error displayed "Chat Validation Message Failure". The chat feature works normally after everyone who got kicked out join and chat, but when another new player tries to chat, the problem happens again.

**To Reproduce**
1. Join the server with EasyAuth installed
2. Have another player join the server
3. Make the new player chat
5. Everyone gets kicked out with the "Chat message Validation Failure".

**Expected behavior**
New players who joined the server does not get kicked out with everyone in it when they chat.

**Additional context**
Note that by "new players", I don't just mean players who join the server for the first time. By this, I mean players who have their session expired (since once everyone gets kicked out, when they all join and chat (they all have unexpired sessions), it works normally until another player with a new session join". Also, I should note that I enabled premiumAutoLogin, hideUnauthenticatedPLayersFromPlayerList and spawnOnJoin. I'll just say that the server provider is Aternos, because maybe that's what's causing it, although I doubt it.

**Comment by NikitaCartes** [comment]
Thanks for detailed issue!

Just disable force-secure-profile in server.properties, it would help :)

**Comment by GitHubbingOuttaHere** [comment]
I'll try disabling that. I'll come back later to tell if it works. And yeah, thanks for your time!

**Comment by GitHubbingOuttaHere** [comment]
Weird... the only option I see in Aternos' `server.properties` in Files related to what you said is `enforce-secure-profile`. However it is already set to `false`. I will try to disable some options in the mod, maybe one of them is the root cause of the problem. Unless there's another option I'm just not seeing in the Aternos control board?

**Comment by NikitaCartes** [comment]
Yes, it should be `enforce-secure-profile`, you are right.

It's strange that it's not helping. You can try to install this mod: https://modrinth.com/mod/no-chat-reports

**Comment by GitHubbingOuttaHere** [comment]
Did some experiments recently, but to no avail. I'll try again with the mod, see if that would fix the problem.

**Comment by GitHubbingOuttaHere** [comment]
Sorry for not immediately responding but seems like the problem was solved by adding No Chat Reports, but I should mention that I also disabled `hideUnauthenticatedPlayersFromPlayerList` and `spawnOnJoin`, so I'm not 100% sure if the mod helped. Buy yeah, so far, the players are not complaining about the error. And yeah, thanks for your help, really appreciate it.
